version: "3.8"

services:

  scrapyd:
    image: cyliaai/scrapyd
    ports:
      - target: 6800
        published: 6800
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: /opt/scrapyd/data
        target: /var/lib/scrapyd
    networks:
      - caddy_public
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  caddy_public:
    external: true
