version: '3.9'

services:
  drone:
    image: drone/drone:2
    volumes:
      - ./dronedata:/data
    environment:
      - DRONE_DATABASE_DRIVER=sqlite3
      - DRONE_DATABASE_DATASOURCE=/data/database.sqlite
      - DRONE_RPC_SECRET=c0feb88a3cd153cc1f7446a8830ee587
      - DRONE_COOKIE_TIMEOUT=720h
      - DRONE_CRON_DISABLED=true
      - DRONE_OPEN=true
      - DRONE_NETWORK=caddy_public
      - DRONE_ADMIN=cylia-admin
      - DRONE_USER_CREATE=username:cylia-admin,admin:true
      - DRONE_SERVER_PORT=:80
      - DRONE_GIT_ALWAYS_AUTH=true
      - DRONE_SERVER_HOST=drone.cylia.cloud
      - DRONE_HOST=https://drone.cylia.cloud
      - DRONE_SERVER_PROTO=https
      - DRONE_TLS_AUTOCERT=false
      - DRONE_AGENTS_ENABLED=true
      - DRONE_GITHUB_CLIENT_ID=efc9c213a2da4528556d
      - DRONE_GITHUB_CLIENT_SECRET=08c3b11deffef4ef0950abf229fcff40d9d4827c
    networks:
      - caddy_public
    ports:
      - "8005:80"
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure 

  runner:
    image: drone/drone-runner-docker:latest
    command: agent
    depends_on:
      - drone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_SERVER=https://drone.cylia.cloud
      - DRONE_RPC_HOST=drone.cylia.cloud
      - DRONE_RPC_PROTO=https
      - DRONE_RPC_SECRET=c0feb88a3cd153cc1f7446a8830ee587
      - DRONE_RUNNER_CAPACITY=10
      - DRONE_RUNNER_NAME=drone-cylia-runner
      - DRONE_RUNNER_NETWORKS=caddy_public
      - DRONE_RUNNER_NETWORK_OPTS=com.docker.network.drive.mtu:1442
    networks:
      - caddy_public
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    
networks:
  caddy_public:
    external: true

volumes:
  dronedata: